# To run the tasks with any other user with sudo privileges
# ansible_user: ansible
# ansible_become_pass: 'admin'

ansible_become: true

# User Name from where ansible is running
ansible_control_node_user: admin

