---
- name:
    "service : restart"
  service:
    state: "restarted"
    name: "airflow-{{ item.key }}"
  when:
    "item.value.state | default('started') != 'stopped'"
  with_dict:
    "{{ airflow_services }}"
  become:
    true

