---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: download repo file
  shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  shell: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt: name={{ item }} state=latest
  with_items:
    - postgresql-9.6
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Make change in postgresql.conf file 
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    mode: 0644
    owner: postgres
    group: postgres 

- name: Restart Postgresql
  service: name=postgresql state=restarted


- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
               name={{ db_user }}
               password={{ db_password }}
               encrypted=yes
               priv=ALL
               state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{ db_user }}
               role_attr_flags=NOSUPERUSER,NOCREATEDB
               state=present
