---

- name: Install python-apt package
  become: true
  apt: 
    name: python-apt
    state: present
    update_cache: true

- name: Create Ambari repo
  command: wget http://public-repo-1.hortonworks.com/ambari/ubuntu18/2.x/updates/2.7.4.0/ambari.list -O /etc/apt/sources.list.d/ambari.list

- name: Add Ambari key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: B9733A7A07513CAD

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
 
- name: Install ambari-agent
  become: true
  apt:
    name: ambari-agent
    state: present
    update_cache: true

#- name: Set the Ambari Server in the agent configuration
#  lineinfile:
#    path: /etc/ambari-agent/conf/ambari-agent.ini
#    regexp: "^hostname="
#    line: "hostname={{ hostvars[groups['ambari-server']|first]['ansible_fqdn'] }}"
#    state: present
#  notify: Restart ambari-agent

- meta: flush_handlers

- name: Make sure the ambari-agent service is started
  service:
    name: ambari-agent
    state: started

- name: Make sure the ambari-agent service is enabled
  service:
    name: ambari-agent
    enabled: yes
  ignore_errors: true
