---

- name: Apply the ambari-agent role to the hadoop-cluster group
  hosts: localhost
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-agent

- name: Apply the ambari-server role to the ambari-server group
  hosts: localhost
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-server
