---
#- import_playbook: "set_variables.yml"
#  tags: always

- name: Apply the database role to the ambari-server group
  hosts: localhost
  any_errors_fatal: true
  become: yes
  roles:
    - role: database
      when: database != "embedded" and not database_options.external_hostname|default('')
  tags: database
