---

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - ubuntu-18.04.yml
        - defaults.yml
      paths:
        - ../ambari-server/vars

- name: Install ambari-server
  become: true
  apt:
    name: ambari-server
    state: present
    update_cache: true

#- meta: flush_handlers
- name: server setup
  command: ambari-server setup -s

- name: Make sure the ambari-server service is started
  service:
    name: ambari-server
    state: started

- name: Make sure the ambari-server service is enabled
  service:
    name: ambari-server
    enabled: yes
  ignore_errors: true

