---

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - defaults.yml
      paths:
        - ../ambari-server/vars

- name: Install mysql-connector-jar
  become: true
  apt:
    name: libmysql-java
    state: present
    update_cache: true


- name: Install ambari-server
  become: true
  apt:
    name: ambari-server
    state: present
    update_cache: true

#- meta: flush_handlers
- name: server setup
  command: ambari-server setup -s

- name: Make sure the ambari-server service is started
  service:
    name: ambari-server
    state: started

- name: Make sure the ambari-server service is enabled
  service:
    name: ambari-server
    enabled: yes
  ignore_errors: true

- name: create symbolic link for mysql-connector-jar
  shell: "cd /var/lib/ambari-server/resources/ && ln -s /usr/share/java/mysql-connector-java.jar mysql-connector-java.jar"

