---

- name: Upload single-node blueprint
  template: src=blueprint-single-node.j2 dest=/tmp/cluster_blueprint mode=0644

- name: Upload single-node cluster creation template
  template: src=cluster-single-node.j2 dest=/tmp/cluster_template mode=0644

#- name: Upload HDP Repo
#  template: src=hdprepo.j2 dest=/tmp/hdprepo mode=0644
#  when: custom_repo

#- name: Read the repo
#  slurp: src=/tmp/hdprepo
#  register: hdprepo
#  when: custom_repo

#- name: modify repo base_url
#  uri: url=http://{{ ansible_fqdn }}:8080/{{ custom_repo_target }}
#       method=PUT
#       force_basic_auth=yes
#       user=admin
#       password=admin
#       HEADER_X-Requested-By="ambari"
#       body=" {{ hdprepo.content | b64decode }}"
#       body_format=raw
#       status_code=200,201,202
#  when: custom_repo

- name: Fetch the blueprint
  slurp: src=/tmp/cluster_blueprint
  register: cluster_blueprint

- name: Make sure the blueprint doesn't already exist
  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/blueprints/cluster_blueprint
       method=DELETE
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  ignore_errors: true

- name: Register the blueprint with the Ambari server
  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/blueprints/cluster_blueprint
       method=POST
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body=" {{ cluster_blueprint.content | b64decode }}"
       body_format=raw
       status_code=200,201,202

- name: Slurp the cluster creation template
  slurp: src=/tmp/cluster_template
  register: cluster_template

#- name: Create the cluster instance
#  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/clusters/cluster1
#       method=POST
#       force_basic_auth=yes
#       user=admin
#       password=admin
#       HEADER_X-Requested-By="ambari"
#       body=" {{ cluster_template.content | b64decode }}"
#       body_format=raw
#       status_code=200,201,202

- name: "Create Cluster"
  become: true
  shell: "curl --user admin:admin -H 'X-Requested-By:ambari' -X POST http:/{{ ansible_fqdn }}:8080/api/v1/clusters/cluster1 -d @/tmp/cluster_template.json"


- name: Change Ambari admin user password
  uri: url=http://{{ ansible_fqdn }}:8080/api/v1/users/admin
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body=' {"Users":{ "password":"{{ admin_password }}", "old_password":"admin"}}'
       body_format=raw
       status_code=200,201,202
  when: admin_password != 'admin'
