---

- name: "Post Cluster Blueprint"
  become: true
  shell: "curl --user admin:admin -H 'X-Requested-By:ambari' -X POST http://{{ ansible_fqdn }}:8080/api/v1/blueprints/dimagi-uat-cluster-1 -d @/tmp/single_node.json"


- name: "Create Cluster"
  become: true
  shell: "curl --user admin:admin -H 'X-Requested-By:ambari' -X POST http:/{{ ansible_fqdn }}:8080/api/v1/clusters/dimagi-uat-cluster-1 -d @/tmp/single_node.json"

